spring:
  application:
    name : zuul

server:
  port : 6005

eureka:
  client:
    service-url:
      defaultZone : http://localhost:5000/eureka/

zuul:
  routes:
    sbService :
      path : /sbService/**
      serviceId : springcloudService